<a href="https://colab.research.google.com/github/zahradwihanumaprilia-oss/UTS-BIG-DATA-Zahra-Dwi-Hanum-Aprillia-14022300062-6C-SI-/blob/main/Zahra_Dwi_Hanum_Aprilia_UTS_BIG_DATA__14022300062_6C_SI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -q google-play-scraper transformers torch pandas

In [26]:
from google_play_scraper import reviews, Sort
import pandas as pd
from transformers import pipeline

# 1. PROSES SCRAPING (Mengambil ulasan Info BMKG)
print("Sedang mengambil ulasan dari Info BMKG...")
result, _ = reviews(
    'com.Info_BMKG', # ID aplikasi Info BMKG
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=100, # Jumlah ulasan yang diambil
    filter_score_with=None
)

# 2. PROSES TRANSFORMER (Load AI IndoRoBERTa)
print("Memuat model AI IndoRoBERTa untuk membaca data...")
# Menggunakan model IndoRoBERTa khusus sentimen bahasa Indonesia
model_name = "w11wo/indonesian-roberta-base-sentiment-classifier"
nlp_ai = pipeline("sentiment-analysis", model=model_name)

# 3. ANALISIS DATA
data_final = []
for review in result:
    teks = review['content']
    # AI menganalisis teks ulasan (max 512 karakter)
    hasil_ai = nlp_ai(teks[:512])[0]

    data_final.append({
        'userName': review['userName'],
        'score': review['score'],
        'at': review['at'],
        'content': teks,
        'Analisis_AI': hasil_ai['label'],
        'Skor_Kepastian': round(hasil_ai['score'], 4)
    })

# 4. SIMPAN DAN TAMPILKAN
df = pd.DataFrame(data_final)
df.to_csv('hasil_uts_bmkg_ai.csv', index=False)
print("Selesai! File 'hasil_uts_bmkg_ai.csv' telah dibuat.")
df.head() # Menampilkan pratinjau hasil

Sedang mengambil ulasan dari Info BMKG...
Memuat model AI IndoRoBERTa untuk membaca data...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: w11wo/indonesian-roberta-base-sentiment-classifier
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Selesai! File 'hasil_uts_bmkg_ai.csv' telah dibuat.

,userName,score,at,content,Analisis_AI,Skor_Kepastian
0,khoirul keong,1,2026-04-29 13:00:21,lebih bagus apk cuaca aplikasi lainnya tapi mi...,negative,0.9779
1,Ade Chandra,1,2026-04-28 22:18:02,Ga bs dibuka,negative,0.9544
2,Rahmat Chanel,2,2026-04-28 19:16:50,tolong di perbaiki sering eror,negative,0.9401
3,Muhammad Azrielfirdaus,4,2026-04-27 13:59:14,bagus,positive,0.7057
4,Damar,4,2026-04-27 12:25:43,Oke tapi menurut saya UI menu hamburgernya (ga...,negative,0.9643

In [27]:
display(df)

,userName,score,at,content,Analisis_AI,Skor_Kepastian
0,khoirul keong,1,2026-04-29 13:00:21,lebih bagus apk cuaca aplikasi lainnya tapi mi...,negative,0.9779
1,Ade Chandra,1,2026-04-28 22:18:02,Ga bs dibuka,negative,0.9544
2,Rahmat Chanel,2,2026-04-28 19:16:50,tolong di perbaiki sering eror,negative,0.9401
3,Muhammad Azrielfirdaus,4,2026-04-27 13:59:14,bagus,positive,0.7057
4,Damar,4,2026-04-27 12:25:43,Oke tapi menurut saya UI menu hamburgernya (ga...,negative,0.9643
...,...,...,...,...,...,...
95,"Maldi Merantaw, 890",5,2026-02-27 12:41:36,Ok,neutral,0.8644
96,fikar pasambuna,1,2026-02-27 10:53:48,"Tingkat Akurasi lemah, 40%an akurasinya. Buat ...",negative,0.9866
97,Dapun_ Gaming,1,2026-02-27 05:50:48,"apknya bagus,tapi sayang sering berhenti digam...",negative,0.7276
98,Sandy Eatdah,5,2026-02-26 15:44:33,"good, tapi untuk bbrp waktu ngebug jadi khawat...",negative,0.6051
99,Rudi Priyanto,1,2026-02-26 02:21:13,tidak akurat,negative,0.9978

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive